---
- name: setup dns records in cloudflare
  cloudflare_dns:
    account_email: "{{ srv_cdn_cloudflare_email }}"
    account_api_token: "{{ srv_cdn_cloudflare_token }}"
    zone: "{{ item.zone }}"
    record: "{{ item.name }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    proxied: "{{ item.proxied |default(false) |bool }}"
  delegate_to: localhost
  loop: "{{ records |flatten }}"
  loop_control:
    loop_var: item
    label: "{{ item.zone }}/{{ item.name }} {{ item.type }} {{ value_label }} [{{ proxied_label }}]"
  vars:
    value_label: "{{ item.value |default('-') }}"
    proxied_label: "{{ item.proxied |default(false) |bool |ternary('proxied','direct') }}"
  when: item.value |default('',true)
        and srv_cdn_cloudflare_email is defined
        and srv_cdn_cloudflare_token is defined
        and srv_cdn_cloudflare_token |default('',true)
...
