---
- name: setup cloudfront distributions for cdn
  import_tasks: cloudfront.yml
  when: srv_cdn_cloudfront
  tags:
    - srv_cdn_cloudfront
    - srv_cdn_all

- name: create directory for nginx mixin configurations
  file:
    path: /etc/nginx/mixin.d
    state: directory
  become: true
  tags:
    - srv_cdn_nginx
    - srv_cdn_all

- name: configure simple cdn in nginx
  template:
    src: cdn.conf
    dest: /etc/nginx/sites-enabled/cdn.conf
  become: true
  notify: reload nginx service
  tags:
    - srv_cdn_nginx
    - srv_cdn_all

- name: apply new nginx settings
  meta: flush_handlers
  tags:
    - srv_cdn_all
...
