---
- name: setup dns records in cloudflare for cdn
  import_tasks: cloudflare.yml
  vars:
    records: "{{ srv_cdn_cloudflare |default([]) }}"
  when: srv_cdn_cloudflare is defined
  tags:
    - srv_cdn_cloudflare
    - srv_cdn_all

- name: setup cloudfront distributions for cdn
  import_tasks: cloudfront.yml
  when: srv_cdn_cloudfront |default([],true)
  tags:
    - srv_cdn_cloudfront
    - srv_cdn_all

- name: create directory for nginx mixin configurations
  file:
    path: "{{ nginx_root_dir }}/mixin.d"
    state: directory
  become: true
  tags:
    - srv_cdn_nginx
    - srv_cdn_all

- name: configure cdn mappings in nginx (skip in check mode)
  template:
    src: cdn.conf
    dest: "{{ nginx_site_dir }}/cdn.conf"
    mode: 0644
  become: true
  notify: reload nginx service
  ## this task depends on "cloudfront distributions" failing in check mode
  when: not ansible_check_mode
  tags:
    - srv_cdn_nginx
    - srv_cdn_all

- name: configure simple cdn site in nginx
  template:
    src: cdn.inc
    dest: "{{ nginx_site_dir }}/cdn.inc"
    mode: 0644
  become: true
  notify: reload nginx service
  tags:
    - srv_cdn_nginx_site
    - srv_cdn_nginx
    - srv_cdn_all

- name: apply new nginx settings
  meta: flush_handlers
  tags:
    - srv_cdn_all
...
