---
- name: directory for nginx backend configurations
  file:
    path: /etc/nginx/bastion.d
    state: directory
  become: true
  tags: srv_mirror_all

- name: configure site mirroring
  template:
    src: mirrors.conf
    dest: /etc/nginx/sites-enabled/mirrors.conf
  become: true
  notify: reload nginx service
  tags: srv_mirror_all

- name: apply new nginx settings
  meta: flush_handlers
  tags: srv_mirror_all
...
